<?php
    
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Database\Database;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use Drupal\Core\Link;


function biz_webforms_webform_submission_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
    switch ($form_id) {
        case "webform_submission_turn_in_poachers_polluters_add_form":
            $form['actions']['submit']['#submit'][] = 'biz_webforms_submit';
            break;
        default:
            break;
    }
}

function biz_webforms_submit(&$form, FormStateInterface &$form_state){
  drupal_set_message(t('Your report was successfully made to the Government of Yukon.'), 'status');
}


function biz_webforms_modules_installed($modules) {
  if (in_array('site_tipp', $modules)) {
    \Drupal::configFactory()->getEditable('system.site')
                            ->set('page.front', '/tipp')
                            ->save();
  }
}